-- begin CUSTOMERS_CUSTOMER
create unique index IDX_CUSTOMERS_CUSTOMER_UNIQ_EMAIL on CUSTOMERS_CUSTOMER (EMAIL)^
-- end CUSTOMERS_CUSTOMER
-- begin CUSTOMERS_ORDER
alter table CUSTOMERS_ORDER add constraint FK_CUSTOMERS_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUSTOMERS_CUSTOMER(ID)^
create unique index IDX_CUSTOMERS_ORDER_UNIQ_ORDER_NUMBER on CUSTOMERS_ORDER (ORDER_NUMBER)^
create index IDX_CUSTOMERS_ORDER_ON_CUSTOMER on CUSTOMERS_ORDER (CUSTOMER_ID)^
-- end CUSTOMERS_ORDER
-- begin CUSTOMERS_REGULAR_CUSTOMER_CARD
alter table CUSTOMERS_REGULAR_CUSTOMER_CARD add constraint FK_CUSTOMERS_REGULAR_CUSTOMER_CARD_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUSTOMERS_CUSTOMER(ID)^
create index IDX_CUSTOMERS_REGULAR_CUSTOMER_CARD_ON_CUSTOMER on CUSTOMERS_REGULAR_CUSTOMER_CARD (CUSTOMER_ID)^
-- end CUSTOMERS_REGULAR_CUSTOMER_CARD
