alter table CUSTOMERS_REGULAR_CUSTOMER_CARD alter column TOTAL_OF_ALL_ORDERS rename to TOTAL_OF_ALL_ORDERS__U57527 ^
alter table CUSTOMERS_REGULAR_CUSTOMER_CARD add column TOTAL_OF_ALL_ORDERS decimal(19, 2) ;
