alter table CUSTOMERS_ORDER add constraint FK_CUSTOMERS_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUSTOMERS_CUSTOMER(ID);
create unique index IDX_CUSTOMERS_ORDER_UNIQ_ORDER_NUMBER on CUSTOMERS_ORDER (ORDER_NUMBER);
create index IDX_CUSTOMERS_ORDER_ON_CUSTOMER on CUSTOMERS_ORDER (CUSTOMER_ID);
